on: [push]

jobs:
  build_cv_rus_job:
    runs-on: ubuntu-latest
    name: A job to build CV into the PDF
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Build
        id: build
        uses: ./
      - name: Artifacts
        id: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: |
            ./cv_rus.pdf
